/**
 * Default seed list used on first app visit (when localStorage is empty).
 * Users can replace this list by importing an Excel/CSV file.
 */
export const DEFAULT_SITES = [
  { name: "ABE", url: "https://abe.br.trackit.host/healthz" },
  { name: "CJR", url: "https://cjr.br.trackit.host/healthz" },
  { name: "ABF", url: "https://abf.br.trackit.host/healthz" },
  { name: "CVF", url: "https://cvf.br.trackit.host/healthz" },
  { name: "BIE", url: "https://bie.br.trackit.host/healthz" },
  { name: "ABR", url: "https://abr.br.trackit.host/healthz" },
  { name: "GRR", url: "https://grr.br.trackit.host/healthz" },
  { name: "BRF", url: "https://brf.br.trackit.host/healthz" },
  { name: "VAF", url: "https://vaf.br.trackit.host/healthz" },
  { name: "MEN", url: "https://men.br.trackit.host/healthz" },
  { name: "INP", url: "https://inp.br.trackit.host/healthz" },
  { name: "OXE", url: "https://oxe.br.trackit.host/healthz" },
  { name: "TMP", url: "https://tmp.br.trackit.host/healthz" },
  { name: "ENB", url: "https://enb.br.trackit.host/healthz" },
  { name: "BWP", url: "https://bwp.br.trackit.host/healthz" },
  { name: "SDB", url: "https://sdb.br.trackit.host/healthz" },
  { name: "RCF", url: "https://rcf.br.trackit.host/healthz" },
  { name: "SML", url: "https://sml.br.trackit.host/healthz" },
  { name: "RXR", url: "https://rxr.br.trackit.host/healthz" },
  { name: "RFT", url: "https://rft.br.trackit.host/healthz" },
  { name: "CMA", url: "https://cma.cl.trackit.host/healthz" },
  { name: "CNE", url: "https://cne.br.trackit.host/healthz" },
  { name: "GLM", url: "https://glm.br.trackit.host/healthz" },
  { name: "CST", url: "https://cst.br.trackit.host/healthz" },
  { name: "VAP", url: "https://vap.br.trackit.host/healthz" },
  { name: "VLI", url: "https://vli.br.trackit.host/healthz" },
  { name: "FTM", url: "https://ftm.br.trackit.host/healthz" },
  { name: "AGP", url: "https://agp.br.trackit.host/healthz" },
  { name: "LDC", url: "https://ldc.br.trackit.host/healthz" },
  { name: "DEX", url: "https://dex.br.trackit.host/healthz" },
  { name: "EDC", url: "https://edc.br.trackit.host/healthz" },
  { name: "CBM", url: "https://cbm.br.trackit.host/healthz" },
  { name: "JFI", url: "https://jfi.br.trackit.host/healthz" },
  { name: "KLB", url: "https://klb.br.trackit.host/healthz" },
  { name: "CNB", url: "https://cnb.br.trackit.host/healthz" },
  { name: "ELD", url: "https://eld.br.trackit.host/healthz" },
  { name: "SYL", url: "https://syl.br.trackit.host/healthz" },
  { name: "MTM", url: "https://mtm.br.trackit.host/healthz" },
  { name: "TER", url: "https://ter.br.trackit.host/healthz" },
  { name: "ARC", url: "https://arc.br.trackit.host/healthz" },
  { name: "WST", url: "https://wst.br.trackit.host/healthz" },
  { name: "ANG", url: "https://ang.br.trackit.host/healthz" },
  { name: "VRC", url: "https://vrc.br.trackit.host/healthz" },
  { name: "AMR", url: "https://amr.br.trackit.host/healthz" },
  { name: "TNS", url: "https://tns.br.trackit.host/healthz" },
  { name: "VPC", url: "https://vpc.br.trackit.host/healthz" },
]
