/**
 * Default seed list used on first app visit (when localStorage is empty).
 * Users can replace this list by importing an Excel/CSV file.
 */
export const DEFAULT_SITES = [
  { name: "ABE", url: "https://abe.br.trackit.host/Login" },
  { name: "CJR", url: "https://cjr.br.trackit.host/Login" },
  { name: "ABF", url: "https://abf.br.trackit.host/Login" },
  { name: "CVF", url: "https://cvf.br.trackit.host/Login" },
  { name: "BIE", url: "https://bie.br.trackit.host/Login" },
  { name: "ABR", url: "https://abr.br.trackit.host/Login" },
  { name: "GRR", url: "https://grr.br.trackit.host/Login" },
  { name: "BRF", url: "https://sso.aiko.digital/realms/brf/protocol/openid-connect/auth?client_id=trackit&redirect_uri=https%3A%2F%2Fbrf.br.trackit.host%2Fsignin-oidc&response_type=code&scope=openid%20profile&code_challenge=G1g6pJqZ5ezlxXNI7bAqCV_IxuCtLLvec04HyHT7iDs&code_challenge_method=S256&response_mode=form_post&nonce=639088357382104609.NzZiZTEwMzUtOTNhNi00MTllLTg0MzYtODRjOTkwMzBjZjcxNDljMDFkNDItYjNjMC00OTI1LThmMjktOWQ0MjkwMzllOWRj&state=CfDJ8EIOKAnzQHlBsF4ocgkVwN5-2Eb9SvWGivFu-Xtz2SddGXKN-feaBfAT2oW1RVGv8IJU8dEI8wXMUcp41Kyli704nfdF0FROqxoiJHj-OqY9xXXG36V7CnMWtePSEQYIK9xyfj1DHiRQruonYCE2EA3kTQ6vhJW7-NkUg3xXl_mdU64ijKyzXrR775Jrj1bThPZTmf_EsJ_hTaP6EmtrlJ-BYWmtsw3TEO-plxrCoYTRnUu6m_xTROiOZ_TMvXqb6X7Jh30Kf-ssNFHy-4dacKAUKYb4uASciSSjOZTedar7jofdhFpcVc-IuA2f0blarhWcEgz4uwhzwny0QVv7xhPee8GvRd2IAkTxOHxW4J7w2qogxs57H1UxibuBmtYCvg&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0" },
  { name: "VAF", url: "https://vaf.br.trackit.host/Login" },
  { name: "MEN", url: "https://men.br.trackit.host/Login" },
  { name: "INP", url: "https://inp.br.trackit.host/Login" },
  { name: "OXE", url: "https://oxe.br.trackit.host/Login" },
  { name: "TMP", url: "https://tmp.br.trackit.host/Login" },
  { name: "ENB", url: "https://enb.br.trackit.host/Login" },
  { name: "BWP", url: "https://bwp.br.trackit.host/Login" },
  { name: "SDB", url: "https://sdb.br.trackit.host/Login" },
  { name: "RCF", url: "https://rcf.br.trackit.host/Login" },
  { name: "SML", url: "https://sml.br.trackit.host/Login" },
  { name: "RXR", url: "https://rxr.br.trackit.host/Login" },
  { name: "RFT", url: "https://rft.br.trackit.host/Login" },
  { name: "CMA", url: "https://cma.cl.trackit.host/Login" },
  { name: "GLM", url: "https://glm.br.trackit.host/Login" },
  { name: "CST", url: "https://sso.aiko.digital/realms/cst/protocol/openid-connect/auth?client_id=trackit&redirect_uri=https%3A%2F%2Fcst.br.trackit.host%2Fsignin-oidc&response_type=code&scope=openid%20profile&code_challenge=XxFjioC1AEbNHrzG8fxlfHFLHG5qns7P-uaOZyrVK7k&code_challenge_method=S256&response_mode=form_post&nonce=639088358239091738.MzFjYmMzYTktN2ZjZi00OTQ3LWFiMzItMzBjZTMxZmY1NTU5NTk2NDE1ZTItYTJhNS00MmE3LTlkNmYtNmE1MmIwZTdmMDg2&state=CfDJ8MAKlnMx9ChEuv0hbJGbJxQtcpRFMLPc7aLdFRYFGlGGkdDe5trsBP_eB0MWKCs_9kF3EAN7aiPyxFfX9zM4OejldSCMHLa2alaWqP3jboRRi1DQY09AcH0MigIqWb0cF4_GRTsxZ3PKiGEG950KBR7AUXaee29PSWWlx6GhSvcrqhDvn8gEiiGzJ5JP_4v6J6dkCT2-EgXbKzIZgFrxOOTxZZyOR-Eckk7_oOuJRNMZGkb9GbpB5u_3wR7a9PjyuiBWvMrvbPDUtlKdZ_mhnNejBr8u3_58_WlphF0YxynB9GWXWLnbsHn9YzmBJU2O6xtPY5DUxlrVuJmC7H9OEpreZtrZ6FB6cnzzfNsw-Z6_NeC0v0qg4vV3sbAk9EhOeQ&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0" },
  { name: "VAP", url: "https://vap.br.trackit.host/Login" },
  { name: "FTM", url: "https://ftm.br.trackit.host/Login" },
  { name: "AGP", url: "https://agp.br.trackit.host/Login" },
  { name: "LDC", url: "https://ldc.br.trackit.host/Login" },
  { name: "DEX", url: "https://dex.br.trackit.host/Login" },
  { name: "EDC", url: "https://edc.br.trackit.host/Login" },
  { name: "CBM", url: "https://sso.aiko.digital/realms/cbm/protocol/openid-connect/auth?client_id=trackit&redirect_uri=https%3A%2F%2Fcbm.br.trackit.host%2Fsignin-oidc&response_type=code&scope=openid%20profile&code_challenge=fGY5CpqlbMBBxcPuHHY3e7q055R_G35siLuut-BtMpQ&code_challenge_method=S256&response_mode=form_post&nonce=639088358758608639.MmVmNjNiOTctYTZlNi00YzM2LTkwY2UtMmQwZDIzOWM1YTAwYjIyYjQ1M2UtNjVkOS00MzMyLTgxZmYtMThlN2NlYTNkNDBh&state=CfDJ8AXwpNJStE9GpvjFwiuWCiXPhvskSZpAX3LGYCkjzrBZ_2RNlBu0LKdOKGkfVewwMIwa9eqowK2Mp16yHdcVdNPBsaI1Pjn3gY6BDOB4LYD8WiR5Mnu1XzErVDam5_qiCbkeJb6JsEopNOSqg_ooIfQT7MB0qEMa7BIWSlYIoZ6erAhHd6CmR-uGmh-VpmKx6ZzlPp8nJMd27l2ZnSo7FXlOptpRKUvp5jUoNRsIsTw8wIPPreMeLvZmaAUaDOXWpBdlOpNwv2SlDiAm8YzUjjBcRO0Stf53oPWH1YtGQXmBgLW2VE1FfHsvFPbg_T7EfHB_WuV3Rk1utL4N3S_zdu-R6pgt8xcqp3-Rs4VKLFTwesETSnz7J0ytw7p4uh4N_g&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0" },
  { name: "JFI", url: "https://jfi.br.trackit.host/Login" },
  { name: "KLB", url: "https://klb.br.trackit.host/Login" },
  { name: "CNB", url: "https://cnb.br.trackit.host/Login" },
  { name: "ELD", url: "https://eld.br.trackit.host/Login" },
  { name: "SYL", url: "https://syl.br.trackit.host/Login" },
  { name: "MTM", url: "https://mtm.br.trackit.host/Login" },
  { name: "TER", url: "https://ter.br.trackit.host/Login" },
  { name: "ARC", url: "https://sso.aiko.digital/realms/arc/protocol/openid-connect/auth?client_id=trackit&redirect_uri=https%3A%2F%2Farc.br.trackit.host%2Fsignin-oidc&response_type=code&scope=openid%20profile&code_challenge=5QuQfr6JL7PbbiOj8jl34acxMf2KG6xTjmsnIrVHjpQ&code_challenge_method=S256&response_mode=form_post&nonce=639088359244845051.ZTQ4N2EzZTYtMWZjOC00YzlhLThmZjMtMGJlOTAzM2JhYjAzOGViZDQ1ZWEtOTI2Yi00YWIzLTg1ODktZTg3MDY0ZjQ3NTI0&state=CfDJ8Ipu5Xo4YDdCkXFaiqni7ZrlbJJCWsd7vmuo8WsnTHz9Ex1yJnybps3QALHKr0mXk7K9d-m1qwmTzFjZEN_E_mZkUVvaFUl7LJb2EzshR1R6NUGVhSPDdB9XENlZbhSwsDWmO1-rlLvvjKht6WiZb92ts69wfZxsUgY7d-xJZ-7UM54FcZXaWWyqHEGX4fq-QtbLd4axOZUquNNqmDM5q1Ygwn4qMUoBs4zO55azofM2-KqMgT_pYr_BfUtr77Cc_Bjj2ln7-stMUNaGkiOQKDUaUrVf3jJClBiAaENpnV_JaOY7EjimnelS-tEqeumx1pLtlIw7o9M_U9Vi0IACQlkHKcun6dcssTcAmfLaHTiTwHNwCpj51iE_EVv0I-cnUg&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0" },
  { name: "WST", url: "https://wst.br.trackit.host/Login" },
  { name: "ANG", url: "https://ang.br.trackit.host/Login" },
  { name: "VRC", url: "https://vrc.br.trackit.host/Login" },
  { name: "AMR", url: "https://amr.br.trackit.host/Login" },
  { name: "TNS", url: "https://tns.br.trackit.host/Login" },
  { name: "VPC", url: "https://vpc.br.trackit.host/Login" },
  { name: "GRE", url: "https://gre.aikodigital.io/#/login" },
  { name: "AAO", url: "https://aao.br.trackit.host/Login" },
  { name: "MNL", url: "https://mnl.br.trackit.host/Login" },
  { name: "ATV", url: "https://atv.br.trackit.host/Login" },
]
